title: sylvia
description: Notes and projects
url: "https://intentionallydense.github.io" # will be https://yourusername.github.io

# Collections
collections:
  writing:
    output: true
    permalink: /writing/:slug/
  artifacts:
    output: true
    permalink: /artifacts/:slug/

# Build settings
markdown: Kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:slug/
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "artifacts"
    values:
      layout: "project-app"
